name: Create Release

on:
  push:
    tags:  
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Zip
        run: zip -r release.zip . -x ".git/*" ".github/*" ".gitignore" "README.md"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
